import { NgModule } from '@angular/core';
import {
  MatAutocompleteModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatCardModule,
  MatCheckboxModule,
  MatChipsModule,
  MatDatepickerModule,
  MatDialogModule,
  MatDividerModule,
  MatExpansionModule,
  MatFormFieldModule,
  MatGridListModule,
  MatIconModule,
  MatInputModule,
  MatLineModule,
  MatListModule,
  MatMenuModule,
  MatNativeDateModule,
  MatOptionModule,
  MatPaginatorModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatRadioModule,
  MatSelectModule,
  MatSidenavModule,
  MatSlideToggleModule,
  MatSnackBarModule, MatStepperModule,
  MatTableModule,
  MatTabsModule,
  MatToolbarModule, MatTooltipModule
} from '@angular/material';


const MATERIAL_MODULES = [
  MatOptionModule,
  MatButtonModule,
  MatMenuModule,
  MatToolbarModule,
  MatDialogModule,
  MatFormFieldModule,
  MatGridListModule,
  MatTableModule,
  MatTabsModule,
  MatRadioModule,
  MatIconModule,
  MatCardModule,
  MatChipsModule,
  MatInputModule,
  MatSelectModule,
  MatAutocompleteModule,
  MatSnackBarModule,
  MatSlideToggleModule,
  MatDividerModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatListModule,
  MatLineModule,
  MatStepperModule,
  MatCheckboxModule,
  MatSidenavModule,
  MatExpansionModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatTooltipModule,
  MatButtonToggleModule,
  MatPaginatorModule,
  MatFormFieldModule,
];

@NgModule({
  imports: [ MATERIAL_MODULES ],
  exports: [ MATERIAL_MODULES ]
})
export class MaterialModule { }
